"""Create puppies table.

Revision ID: 744833b5a03b
Revises: 
Create Date: 2021-01-01 10:49:46.609788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744833b5a03b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puppies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puppies')
    # ### end Alembic commands ###
